codecov:
  require_ci_to_pass: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: auto
        threshold: 2%
        informational: true

ignore:
  - "tests/**"
