# konfig Codecov – ignorowanie katalogu GUI w agregacji pokrycia
ignore:
  - "app/gui/**"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
comment: false

