line-length = 100
# Docelowa wersja Pythona
target-version = "py312"

[lint]
# Główne kategorie i zakaz printów (T201)
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort (sortowanie importów)
    "T20", # flake8-print (zakaz printów)
]
# Jeśli coś okaże się zbyt restrykcyjne, dopisz do ignore.
ignore = []

